config/routes.rb
Spina::Engine.routes.draw do
  # Backend
  namespace :admin, path: Spina.config.backend_path do
    root to: "pages#index"

    resource :account do
      member do
        get :style
        get :analytics
        get :social
      end
    end

    get "/settings/:plugin", to: "settings#edit", as: :edit_settings
    patch "/settings/:plugin", to: "settings#update", as: :settings

    resources :users

    # Sessions
    resources :sessions
    get "login" => "sessions#new"
    get "logout" => "sessions#destroy"

    # Passwords
    resources :password_resets

    # Media library
    get 'media_library' => 'images#index', as: "media_library"

    resources :pages do
      get :children, on: :member
      post :sort, on: :collection
    end

    resources :resources, only: [:show, :edit, :update]

    resources :navigations do
      post :sort, on: :member
    end

    resources :attachments do
      collection do
        get 'select/:page_part_id' => 'attachments#select', as: :select
        post 'insert/:page_part_id' => 'attachments#insert', as: :insert
        get 'select_collection/:page_part_id' => 'attachments#select_collection', as: :select_collection
        post 'insert_collection/:page_part_id' => 'attachments#insert_collection', as: :insert_collection
      end
    end

    resources :media_folders

    resources :images do
      collection do
        get 'folder/:id' => 'images#media_folder', as: :media_folder
        put 'folder/:id' => 'images#add_to_media_folder', as: :add_to_media_folder
      end
    end
    get :media_picker, to: 'media_picker#show'
    post :media_picker, to: 'media_picker#select'
  end

  # Sitemap
  resource :sitemap

  # Robots.txt
  get '/robots', to: 'pages#robots', constraints: { format: 'txt' }

  unless Spina.config.disable_frontend_routes
    # Frontend
    root to: "pages#homepage"

    # Pages
    get '/:locale/*id' => 'pages#show', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
    get '/:locale/' => 'pages#homepage', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
    get '/*id' => 'pages#show', as: "page", controller: 'pages', constraints: lambda { |request|
      (!(Rails.env.development? && request.env['PATH_INFO'].starts_with?('/rails/') || request.env['PATH_INFO'].starts_with?("/#{Spina.config.backend_path}") || request.env['PATH_INFO'].starts_with?('/attachments/'))) && request.path.exclude?("rails/active_storage")
    }
  end

end

app/models/spina/setting.rb
module Spina
  class Setting < ApplicationRecord

    validates :plugin, presence: true

  end
end

app/controllers/spina/admin/settings_controller.rb
module Spina
  module Admin
    class SettingsController < AdminController

      before_action :find_or_set_settings
      before_action :set_breadcrumbs

      def edit
        add_breadcrumb t("spina.#{plugin.namespace}.title")
      end

      def update
        if @setting.update_attributes(settings_params)
          redirect_to spina.admin_edit_settings_path(plugin.namespace)
        else
          add_breadcrumb t("spina.#{plugin.namespace}.title")
          render :edit
        end
      end

      private

      def setting_class
        "spina/#{plugin.namespace}/setting".classify.constantize
      end

      def plugin
        Spina::Plugin.find_by(namespace: params[:plugin])
      end
      helper_method :plugin

      def find_or_set_settings
        @setting = setting_class.first_or_create do |setting|
          plugin.settings.each do |attribute, type|
            setting.send("#{attribute}=", (type.is_a?(Hash) ? type.first.last : nil))
          end
        end
        plugin.settings.keys.reject do |x|
          @setting.preferences.keys.map(&:to_sym).include? x
        end.each do |key|
          value = plugin.settings[key].is_a?(Hash) ? plugin.settings[key].first.last : nil
          @setting.send("#{key}=", value)
        end
      end

      def set_breadcrumbs
        add_breadcrumb t('spina.settings.title')
      end

      def settings_params
        params.require(:setting).permit(plugin.settings.keys)
      end

    end
  end
end

app/views/spina/admin/settings/_string_field.html.haml
.horizontal-form-label
  = f.label attribute, t("spina.#{plugin.namespace}.settings.#{attribute}")
.horizontal-form-content
  = f.text_field attribute, placeholder: t("spina.#{plugin.namespace}.settings.#{attribute}_placeholder")

app/views/spina/admin/settings/_wysiwyg_field.html.haml
.horizontal-form-label
  = f.label attribute, t("spina.#{plugin.namespace}.settings.#{attribute}")
.horizontal-form-content
  = render 'spina/admin/shared/rich_text_field', f: f, field: attribute

app/views/spina/admin/settings/edit.html.haml
= form_for @setting, url: admin_settings_path do |f|
  %header#header
    = render partial: 'spina/admin/shared/breadcrumbs'

    #header_actions
      %button.button.button-primary{type: 'submit'}
        = icon('check')
        = t('spina.settings.save')

  .well
    .horizontal-form
      - plugin.settings.each do |key, value|
        .horizontal-form-group= render "#{value.is_a?(Hash) ? value.first.first : value}_field", f: f, attribute: key